"""Variable definitions used in various scripts."""

DISEASE_DICT = {
    1: "Healthy Controls",
    2: "Schizophrenia",
    3: "Bipolar Disorder",
    4: "First Episode of Psychosis",
    5: "Clinical High Risk for Psychosis",
    6: "22q11.2 Deletion With Psychosis",
    7: "22q11.2 Deletion Without Psychosis",
    8: "ADHD - Unspecified",
    9: "Borderline Personality Disorder",
    10: "Osteoartrithic",
    11: "Autism Spectrum Disorder",
    12: "Major Depressive Disorder",
    13: "Anxiety",
    14: "Obsessive Compulsive Disorder",
    15: "Post-Traumatic Stress Disorder",
    16: "Sexual Disfunction of Psychological Origin",
    17: "Alzheimer's Disease",
    18: "Mild Cognitive Impairment",
    19: "Eating disorders",
    20: "ADHD - Hyperactive/Impulsive",
    21: "ADHD - Inattentive",
    22: "ADHD - Combined",
    23: "Prodromal Parkinson's Disease",
    24: "Parkinson's Disease",
    25: "Scans Without Evidence of a Dopaminergic Deficit",
    26: "Significant Memory Concern",
    27: "Early Mild Cognitive Impairment (EMCI)",
    28: "Late Mild Cognitive Impairment (LMCI)",
    888: "Other: Neurologic",
    999: "Other: Psychiatric"
}

COLUMNS_NAME = ['Left-Lateral-Ventricle',
                'Left-Inf-Lat-Vent',
                'Left-Cerebellum-White-Matter',
                'Left-Cerebellum-Cortex',
                'Left-Thalamus-Proper',
                'Left-Caudate',
                'Left-Putamen',
                'Left-Pallidum',
                '3rd-Ventricle',
                '4th-Ventricle',
                'Brain-Stem',
                'Left-Hippocampus',
                'Left-Amygdala',
                'CSF',
                'Left-Accumbens-area',
                'Left-VentralDC',
                'Right-Lateral-Ventricle',
                'Right-Inf-Lat-Vent',
                'Right-Cerebellum-White-Matter',
                'Right-Cerebellum-Cortex',
                'Right-Thalamus-Proper',
                'Right-Caudate',
                'Right-Putamen',
                'Right-Pallidum',
                'Right-Hippocampus',
                'Right-Amygdala',
                'Right-Accumbens-area',
                'Right-VentralDC',
                'CC_Posterior',
                'CC_Mid_Posterior',
                'CC_Central',
                'CC_Mid_Anterior',
                'CC_Anterior',
                'lh_bankssts_volume',
                'lh_caudalanteriorcingulate_volume',
                'lh_caudalmiddlefrontal_volume',
                'lh_cuneus_volume',
                'lh_entorhinal_volume',
                'lh_fusiform_volume',
                'lh_inferiorparietal_volume',
                'lh_inferiortemporal_volume',
                'lh_isthmuscingulate_volume',
                'lh_lateraloccipital_volume',
                'lh_lateralorbitofrontal_volume',
                'lh_lingual_volume',
                'lh_medialorbitofrontal_volume',
                'lh_middletemporal_volume',
                'lh_parahippocampal_volume',
                'lh_paracentral_volume',
                'lh_parsopercularis_volume',
                'lh_parsorbitalis_volume',
                'lh_parstriangularis_volume',
                'lh_pericalcarine_volume',
                'lh_postcentral_volume',
                'lh_posteriorcingulate_volume',
                'lh_precentral_volume',
                'lh_precuneus_volume',
                'lh_rostralanteriorcingulate_volume',
                'lh_rostralmiddlefrontal_volume',
                'lh_superiorfrontal_volume',
                'lh_superiorparietal_volume',
                'lh_superiortemporal_volume',
                'lh_supramarginal_volume',
                'lh_frontalpole_volume',
                'lh_temporalpole_volume',
                'lh_transversetemporal_volume',
                'lh_insula_volume',
                'rh_bankssts_volume',
                'rh_caudalanteriorcingulate_volume',
                'rh_caudalmiddlefrontal_volume',
                'rh_cuneus_volume',
                'rh_entorhinal_volume',
                'rh_fusiform_volume',
                'rh_inferiorparietal_volume',
                'rh_inferiortemporal_volume',
                'rh_isthmuscingulate_volume',
                'rh_lateraloccipital_volume',
                'rh_lateralorbitofrontal_volume',
                'rh_lingual_volume',
                'rh_medialorbitofrontal_volume',
                'rh_middletemporal_volume',
                'rh_parahippocampal_volume',
                'rh_paracentral_volume',
                'rh_parsopercularis_volume',
                'rh_parsorbitalis_volume',
                'rh_parstriangularis_volume',
                'rh_pericalcarine_volume',
                'rh_postcentral_volume',
                'rh_posteriorcingulate_volume',
                'rh_precentral_volume',
                'rh_precuneus_volume',
                'rh_rostralanteriorcingulate_volume',
                'rh_rostralmiddlefrontal_volume',
                'rh_superiorfrontal_volume',
                'rh_superiorparietal_volume',
                'rh_superiortemporal_volume',
                'rh_supramarginal_volume',
                'rh_frontalpole_volume',
                'rh_temporalpole_volume',
                'rh_transversetemporal_volume',
                'rh_insula_volume']

# Convert from Freesurfer labels to formatted region labels
FS2REGION = {'3rd-Ventricle': 'Third ventricle',
             '4th-Ventricle': 'Fourth ventricle',
             'Brain-Stem': 'Brain stem',
             'CC_Anterior': 'Corpus callosum anterior',
             'CC_Central': 'Corpus callosum central',
             'CC_Mid_Anterior': 'Corpus callosum mid. anterior',
             'CC_Mid_Posterior': 'Corpus callosum mid. posterior',
             'CC_Posterior': 'Corpus callosum posterior',
             'CSF': 'Cerebrospinal fluid',
             'Left-Accumbens-area': 'Left nucleus accumbens',
             'Left-Amygdala': 'Left amygdala',
             'Left-Caudate': 'Left caudate',
             'Left-Cerebellum-Cortex': 'Left cerebellum cortex',
             'Left-Cerebellum-White-Matter': 'Left cerebellum white matter',
             'Left-Hippocampus': 'Left hippocampus',
             'Left-Inf-Lat-Vent': 'Left inferior lateral ventricle',
             'Left-Lateral-Ventricle': 'Left lateral ventricle',
             'Left-Pallidum': 'Left pallidum',
             'Left-Putamen': 'Left putamen',
             'Left-Thalamus-Proper': 'Left thalamus proper',
             'Left-VentralDC': 'Left ventral diencephalon',
             'Right-Accumbens-area': 'Right nucleus accumbens',
             'Right-Amygdala': 'Right amygdala',
             'Right-Caudate': 'Right caudate',
             'Right-Cerebellum-Cortex': 'Right cerebellum cortex',
             'Right-Cerebellum-White-Matter': 'Right cerebellum white matter',
             'Right-Hippocampus': 'Right hippocampus',
             'Right-Inf-Lat-Vent': 'Right inferior lateral ventricle',
             'Right-Lateral-Ventricle': 'Right lateral ventricle',
             'Right-Pallidum': 'Right pallidum',
             'Right-Putamen': 'Right putamen',
             'Right-Thalamus-Proper': 'Right thalamus proper',
             'Right-VentralDC': 'Right ventral diencephalon',
             'lh_bankssts_volume': 'Left banks of the superior temporal sulcus',
             'lh_caudalanteriorcingulate_volume': 'Left caudal anterior cingulate cortex',
             'lh_caudalmiddlefrontal_volume': 'Left caudal middle frontal gyrus',
             'lh_cuneus_volume': 'Left cuneus cortex',
             'lh_entorhinal_volume': 'Left entorhinal cortex',
             'lh_frontalpole_volume': 'Left frontal pole',
             'lh_fusiform_volume': 'Left fusiform gyrus',
             'lh_inferiorparietal_volume': 'Left inferior parietal cortex',
             'lh_inferiortemporal_volume': 'Left inferior temporal gyrus',
             'lh_insula_volume': 'Left insula',
             'lh_isthmuscingulate_volume': 'Left isthmus-cingulate cortex',
             'lh_lateraloccipital_volume': 'Left lateral occipital cortex',
             'lh_lateralorbitofrontal_volume': 'Left lateral orbitofrontal',
             'lh_lingual_volume': 'Left lingual gyrus',
             'lh_medialorbitofrontal_volume': 'Left medial orbital frontal cortex',
             'lh_middletemporal_volume': 'Left middle temporal gyrus',
             'lh_paracentral_volume': 'Left paracentral lobule',
             'lh_parahippocampal_volume': 'Left parahippocampal gyrus',
             'lh_parsopercularis_volume': 'Left pars opercularis',
             'lh_parsorbitalis_volume': 'Left pars orbitalis',
             'lh_parstriangularis_volume': 'Left pars triangularis',
             'lh_pericalcarine_volume': 'Left pericalcarine',
             'lh_postcentral_volume': 'Left postcentral gyrus',
             'lh_posteriorcingulate_volume': 'Left posterior cingulate cortex',
             'lh_precentral_volume': 'Left precentral gyrus',
             'lh_precuneus_volume': 'Left precuneus cortex',
             'lh_rostralanteriorcingulate_volume': 'Left rostral anterior cingulate cortex',
             'lh_rostralmiddlefrontal_volume': 'Left rostral middle frontal gyrus',
             'lh_superiorfrontal_volume': 'Left superior frontal gyrus',
             'lh_superiorparietal_volume': 'Left superior parietal cortex',
             'lh_superiortemporal_volume': 'Left superior temporal gyrus',
             'lh_supramarginal_volume': 'Left supramarginal gyrus',
             'lh_temporalpole_volume': 'Left temporal pole',
             'lh_transversetemporal_volume': 'Left transverse temporal cortex',
             'rh_bankssts_volume': 'Right banks of the superior temporal sulcus',
             'rh_caudalanteriorcingulate_volume': 'Right caudal anterior cingulate cortex',
             'rh_caudalmiddlefrontal_volume': 'Right caudal middle frontal gyrus',
             'rh_cuneus_volume': 'Right cuneus cortex',
             'rh_entorhinal_volume': 'Right entorhinal cortex',
             'rh_frontalpole_volume': 'Right frontal pole',
             'rh_fusiform_volume': 'Right fusiform gyrus',
             'rh_inferiorparietal_volume': 'Right inferior parietal cortex',
             'rh_inferiortemporal_volume': 'Right inferior temporal cortex',
             'rh_insula_volume': 'Right insula',
             'rh_isthmuscingulate_volume': 'Right isthmus-cingulate cortex',
             'rh_lateraloccipital_volume': 'Right lateral occipital cortex',
             'rh_lateralorbitofrontal_volume': 'Right lateral orbital frontal cortex',
             'rh_lingual_volume': 'Right lingual gyrus gyrus',
             'rh_medialorbitofrontal_volume': 'Right medial orbital frontal cortex',
             'rh_middletemporal_volume': 'Right middle temporal gyrus',
             'rh_paracentral_volume': 'Right paracentral lobule',
             'rh_parahippocampal_volume': 'Right parahippocampal gyrus',
             'rh_parsopercularis_volume': 'Right pars opercularis',
             'rh_parsorbitalis_volume': 'Right pars orbitalis',
             'rh_parstriangularis_volume': 'Right pars triangularis',
             'rh_pericalcarine_volume': 'Right pericalcarine cortex',
             'rh_postcentral_volume': 'Right postcentral gyrus',
             'rh_posteriorcingulate_volume': 'Right posterior cingulate cortex',
             'rh_precentral_volume': 'Right precentral gyrus',
             'rh_precuneus_volume': 'Right precuneus cortex',
             'rh_rostralanteriorcingulate_volume': 'Right rostral anterior cingulate cortex',
             'rh_rostralmiddlefrontal_volume': 'Right rostral middle frontal gyrus',
             'rh_superiorfrontal_volume': 'Right superior frontal gyrus',
             'rh_superiorparietal_volume': 'Right superior parietal cortex',
             'rh_superiortemporal_volume': 'Right superior temporal gyrus',
             'rh_supramarginal_volume': 'Right supramarginal gyrus',
             'rh_temporalpole_volume': 'Right temporal pole',
             'rh_transversetemporal_volume': 'Right transverse temporal cortex'}
